"""
SOS-512 — Emergency Fail-Safe & Isolation.

Safety measures: suspend agents, sandbox isolation,
runaway detection, resource exhaustion monitoring, operator alerts.
"""

import logging
import time
from dataclasses import dataclass, field

logger = logging.getLogger("core.swarm_os.failsafe")


@dataclass
class FailSafeAlert:
    """An alert generated by the fail-safe system."""

    alert_type: str = ""  # resource_exhaustion, runaway_experiment, agent_anomaly, system_critical
    severity: str = "warning"  # info, warning, critical
    message: str = ""
    timestamp: float = field(default_factory=time.time)
    resolved: bool = False

    def to_dict(self) -> dict:
        return {
            "type": self.alert_type,
            "severity": self.severity,
            "message": self.message,
            "resolved": self.resolved,
        }


class FailSafe:
    """Emergency fail-safe and isolation system."""

    def __init__(
        self,
        max_cpu_threshold: float = 95,
        max_memory_threshold_pct: float = 95,
        max_experiment_duration_hours: float = 4,
        max_agent_error_rate: float = 0.5,
    ):
        self.max_cpu = max_cpu_threshold
        self.max_memory = max_memory_threshold_pct
        self.max_exp_hours = max_experiment_duration_hours
        self.max_error_rate = max_agent_error_rate

        self._paused = False
        self._isolated_agents: set[str] = set()
        self._alerts: list[FailSafeAlert] = []

    def check_resources(self, cpu_pct: float, memory_pct: float) -> FailSafeAlert | None:
        """Check for resource exhaustion."""
        if cpu_pct > self.max_cpu:
            return self._alert(
                "resource_exhaustion",
                "critical",
                f"CPU at {cpu_pct:.0f}% (threshold: {self.max_cpu}%)",
            )
        if memory_pct > self.max_memory:
            return self._alert(
                "resource_exhaustion",
                "critical",
                f"Memory at {memory_pct:.0f}% (threshold: {self.max_memory}%)",
            )
        return None

    def check_experiment(self, exp_id: str, started_at: float) -> FailSafeAlert | None:
        """Check for runaway experiments."""
        runtime_hours = (time.time() - started_at) / 3600
        if runtime_hours > self.max_exp_hours:
            return self._alert(
                "runaway_experiment",
                "warning",
                f"Experiment {exp_id} running for {runtime_hours:.1f}h (limit: {self.max_exp_hours}h)",
            )
        return None

    def check_agent(self, agent_name: str, error_rate: float) -> FailSafeAlert | None:
        """Check for agent anomalies."""
        if error_rate > self.max_error_rate:
            return self._alert(
                "agent_anomaly",
                "warning",
                f"Agent {agent_name} error rate {error_rate:.0%} (limit: {self.max_error_rate:.0%})",
            )
        return None

    def pause_swarm(self, reason: str = "") -> None:
        """Emergency pause all agent activity."""
        self._paused = True
        self._alert("system_critical", "critical", f"Swarm PAUSED: {reason}")
        logger.critical("SWARM PAUSED: %s", reason)

    def resume_swarm(self) -> None:
        self._paused = False
        self._alert("system_critical", "info", "Swarm RESUMED")
        logger.info("Swarm RESUMED")

    def is_paused(self) -> bool:
        return self._paused

    def isolate_agent(self, agent_name: str, reason: str = "") -> None:
        self._isolated_agents.add(agent_name)
        self._alert("agent_anomaly", "warning", f"Agent {agent_name} ISOLATED: {reason}")

    def release_agent(self, agent_name: str) -> None:
        self._isolated_agents.discard(agent_name)

    def is_isolated(self, agent_name: str) -> bool:
        return agent_name in self._isolated_agents

    def _alert(self, alert_type: str, severity: str, message: str) -> FailSafeAlert:
        alert = FailSafeAlert(alert_type=alert_type, severity=severity, message=message)
        self._alerts.append(alert)
        logger.warning("failsafe_alert [%s] %s: %s", severity, alert_type, message)
        return alert

    def get_active_alerts(self) -> list[dict]:
        return [a.to_dict() for a in self._alerts if not a.resolved]

    def resolve_all(self) -> int:
        count = sum(1 for a in self._alerts if not a.resolved)
        for a in self._alerts:
            a.resolved = True
        return count

    def get_stats(self) -> dict:
        active = sum(1 for a in self._alerts if not a.resolved)
        return {
            "paused": self._paused,
            "isolated_agents": len(self._isolated_agents),
            "total_alerts": len(self._alerts),
            "active_alerts": active,
        }
