import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


class LogicValidationError(Exception):
    """Raised when an Execution Plan contains impossible requirements or loops."""

    pass


class ReasoningValidator:
    """
    The "critic." Reviews the finalized Execution Plan generated by the Planner.
    If it detects illogical capability combinations or fatal loop structures, it halts propagation.
    """

    # Allowed system capabilities (Placeholder until Layer 6 Swarm defines them)
    SUPPORTED_CAPABILITIES = {
        "bash",
        "python",
        "filesystem",
        "network_read",
        "read_logs",
        "reasoning",
        "general_agent",
    }

    def validate_plan(self, execution_plan: Dict[str, Any]) -> bool:
        """
        Validates the sub-steps of an execution plan.
        Raises LogicValidationError if the plan is fundamentally flawed.
        """
        steps = execution_plan.get("execution_sequence", [])

        if not steps:
            raise LogicValidationError("Execution Plan contains zero sequence steps.")

        for step in steps:
            reqs = step.get("required_capabilities", [])
            for req in reqs:
                if req not in self.SUPPORTED_CAPABILITIES:
                    raise LogicValidationError(
                        f"Plan requests unsupported capability: '{req}'. Cannot execute."
                    )

        # Future constraint validations go here

        logger.debug(f"Reasoning Validator approved Plan {execution_plan.get('plan_id')}")
        return True
