import logging
import asyncio
from typing import Dict, Any

from src.raphael.core.schemas import SystemEvent, EventType, LayerContext
from src.raphael.core.event_bus import SystemEventBus
from src.raphael.spine.resources import ResourceManager
from src.raphael.spine.safety import SafetyGate, SecurityViolation
from src.raphael.spine.health import HealthMonitor
from src.raphael.spine.identity import PermissionsValidator, PermissionDenied

logger = logging.getLogger(__name__)


class SpineRouter:
    """
    The central regulatory hub for Layer 4.
    Intercepts telemetry to track hardware status via the HealthMonitor.
    Intercepts TASK_SPAWNED events to apply Identity, Safety, and Resource limits
    before pushing them as EXECUTION_APPROVED back to the bus.
    """

    def __init__(self, bus: SystemEventBus):
        self.bus = bus
        self.resource_manager = ResourceManager()
        self.health_monitor = HealthMonitor(self.resource_manager)
        self.safety_gate = SafetyGate()
        self.permissions = PermissionsValidator()
        self.layer_ctx = LayerContext(layer_number=4, module_name="SpineRouter")

    def register_subscriptions(self):
        """Listen to telemetry (Layer 1) and Tasks (Layer 3)."""
        # Subscribe to Telemetry for state updates
        self.bus.subscribe(EventType.OBSERVATION, self.handle_telemetry)
        # Subscribe to Task Spawn for governance gating
        self.bus.subscribe(EventType.TASK_SPAWNED, self.handle_task_proposal)

    async def handle_telemetry(self, event: SystemEvent):
        """Processes hardware telemetry and emits alerts if thresholds are breached."""
        # We only care about telemetry from Layer 1 monitors
        if event.source_layer.module_name != "SystemMonitor":
            return

        alert_msg = self.health_monitor.process_telemetry(event.payload)

        if alert_msg:
            critical_event = SystemEvent(
                event_type=EventType.CRASH_REPORT,
                source_layer=self.layer_ctx,
                priority=10,
                payload={"hardware_alert": alert_msg},
            )
            await self.bus.publish(critical_event)

    async def handle_task_proposal(self, event: SystemEvent):
        """
        Intercepts tasks generated by Layer 3.
        Runs Safety Gate -> Identity Check -> Resource Allocation.
        If all pass, emits an EXECUTION_APPROVED event for Layer 6/7.
        """
        try:
            payload = event.payload

            # 1. Safety Gate
            self.safety_gate.evaluate_payload(payload)

            # 2. Identity Check
            # Assume tasks generated by the user have root wildcard identity for now.
            requester_role = payload.get("assigned_role", "user")

            # Iterate through subtasks to find total required capabilities
            all_caps = []
            for st in payload.get("sub_tasks", []):
                all_caps.extend(st.get("required_capabilities", []))

            self.permissions.evaluate_request(requester_role, list(set(all_caps)))

            # 3. Resource Allocation
            if not self.resource_manager.can_schedule_task(payload):
                self.resource_manager.queue_task(payload)
                return  # Held in queue, not emitting approval yet

            self.resource_manager.allocate(payload)

            # 4. Success. Pass the baton to the Executing layers.
            approved_event = SystemEvent(
                event_type=EventType.EXECUTION_APPROVED,
                source_layer=self.layer_ctx,
                priority=event.priority,
                payload=payload,
                correlation_id=event.event_id,
            )
            await self.bus.publish(approved_event)
            logger.info(f"Layer 4 Spine approved execution for task {payload.get('task_id')}")

        except (SecurityViolation, PermissionDenied) as e:
            logger.critical(f"Task Denied by Governance Policy: {e}")
            denied_event = SystemEvent(
                event_type=EventType.CRASH_REPORT,
                source_layer=self.layer_ctx,
                priority=9,
                payload={"error": str(e), "task_id": event.payload.get("task_id")},
            )
            await self.bus.publish(denied_event)
